### PR TITLE
Update Replace placeholder icon #36

### PR DESCRIPTION
**Pull request by pojith**
I update placeholder for website
if any problem can u inform me i will immediate update

### CODE REVIEW

**Review by suuunly — CHANGES_REQUESTED** [review]
You are missing the `img-384.png` 😄

**Comment by suuunly** [comment]
> can you verfify its my first contribution in the git hub can you help me

I cannot, but you can see it on your own GitHub profile 😃

**Review by suuunly — COMMENTED** [review]
Oh, sorry. I also noticed just now that you used the wrong image for the `img-` files. It should be the one with the white circular background.

The one with the transparent background is only used for the favicon 😄

**Comment by pojith** [comment]
ok how i will resolve

**Comment by suuunly** [comment]
The image `512x512` uses the incorrect image. It should be the one with the round white background :)

**Comment by suuunly** [comment]
And you are missing the `384x384` image 😄

**Comment by pojith** [comment]
> And you are missing the `384x384` image 😄

for this image what would to size

**Comment by suuunly** [comment]
> > And you are missing the `384x384` image 😄
> 
> for this image what would to size

it should be 384x384. As mentioned here:
https://github.com/flowcore-io/open-source-conference-app/issues/36#issuecomment-1964442565

**Comment by pojith** [comment]
can u check new pull request

**Pull request closed without merging**
